### Partie 1 : Listes Python vs tableaux NumPy 

#### 1) Créer une liste Python stockant ces températures; 

In [11]:
import numpy as np
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8 ]
print (temperatures)

[24.5, 25.1, 26.3, 27.0, 25.8]


#### 2) Créer un tableau NumPy équivalent stockant ces températures ;

In [14]:
temperatures = np.array([24.5, 25.1, 26.3, 27.0, 25.8 ])
print(temperatures)

[24.5 25.1 26.3 27.  25.8]


#### 3) Effectuer une multiplication par 2 sur ces deux collections; 

---pour la liste---

In [12]:
mult_liste_temp = temperatures * 2
print(mult_liste_temp)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]


---pour le tableau---

In [15]:
mult_tableau_temp = temperatures * 2
print (mult_tableau_temp)

[49.  50.2 52.6 54.  51.6]


#### 4) Quelle différence observe-t-on ? 

Pour la liste : nous constatons qu'il y'a une duplication de la liste ,les valeurs sont repetes deux fois .
Et pour le tableau : nous constatons un nouveau tableau avec des valeurs multipliees chacune par 2.

### Partie 2 – Création des données 

#### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [31]:
tableau_zero = np.zeros(10)
print(tableau_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [30]:
tableau_un = np.ones(10)
print(tableau_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 3) Créer un tableau de 10 valeurs initialisées à 25. 


In [28]:
val = np.full(10,25)
print(val)

[25 25 25 25 25 25 25 25 25 25]


#### 4) Créer une matrice identité de taille 5 × 5. 

In [27]:
identite = np.eye(5,5)
print(identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [36]:
heures = np.arange(0,24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [38]:
tableau_repartie = np.linspace(20,30,10 , dtype=int)
print(tableau_repartie)

[20 21 22 23 24 25 26 27 28 30]


#### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [69]:
rng = np.random.default_rng(seed=42)
temperature = rng.random(100)
print(temperature)


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
 0.7611397  0.78606431 0.12811363 0.45038594 0.37079802 0.92676499
 0.64386512 0.82276161 0.4434142  0.22723872 0.55458479 0.06381726
 0.82763117 0.6316644  0.75808774 0.35452597 0.97069802 0.89312112
 0.7783835  0.19463871 0.466721   0.04380377 0.15428949 0.68304895
 0.74476216 0.96750973 0.32582536 0.37045971 0.46955581 0.18947136
 0.12992151 0.47570493 0.22690935 0.66981399 0.43715192 0.8326782
 0.7002651  0.31236664 0.8322598  0.80476436 0.38747838 0.2883281
 0.6824955  0.13975248 0.1999082  0.00736227 0.78692438 0.66485086
 0.70516538 0.78072903 0.45891578 0.5687412  0.139797   0.11453007
 0.66840296 0.47109621 0.56523611 0.76499886 0.63471832 0.5535794
 0.55920716 0.3039501  0.03081783 0.43671739 0.21458467 0.40852864
 0.85340307 0.23393949 0.05830274 0.28138389 0.29359376 0.66191651
 0.55703215 0.78389821 0.66431354 0.40638686 0.81402038 0.16697292
 0.02271207 0.09004786 0.72235935 0.46187723 0.16127178 0.5010447

**Explication**: ici pour generer aleatoirement les temperatures de 100 mesures en rendant les resultat reproductibles , on initialise une graine "seed" qu'on choisi de fixer ici 42. cette initialisation permet de fixer un point de depart pour que la machine puisse toujours generer les memes 100 temperatures dans le meme ordre sur n'importe quel machine. 

### Partie 3 – Exploration des tableaux 

#### 1) Créer aléatoirement un tableau représentant les 24 températures d'une journée : 

In [228]:
rng = np.random.default_rng(seed=42)
temp_journee = rng.integers(20,45,24)
print(temp_journee)

[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]


#### 2) Déterminer les propriétés suivantes du tableau 
##### a) nombre de dimensions 

In [229]:
nb_dimensions = temp_journee.ndim
print(nb_dimensions)

1


***explication*** : le resultat indique qu'il y'a une seule dimension c'est a dire une simple liste

##### b) nombre de valeurs ; 

In [230]:
nb_val = temp_journee.size
print(nb_val)

24


***explication*** : ce resultat indique que cette liste contient 24 valeurs

##### c) type des données 

In [231]:
type_donnee = temp_journee.dtype
print(type_donnee)

int64


***explication*** : ce resultat indique le type des donnees et nous pouvons constater que les donnees sont de type float.

##### d) forme du tableau

In [232]:
forme_tab = temp_journee.shape
print(forme_tab)

(24,)


***explication*** : ce resultat nous indique qu'il y'a un seule axe contenant 24 elements

### Partie 4 – Indexation et slicing 

##### 1) la première mesure 

In [233]:
print(temp_journee[0])

22


##### 2) la dernière mesure 

In [234]:
print(temp_journee[-1])

43


##### 3) la température de 8h 

In [235]:
print(temp_journee[8])

25


##### 4) les températures de 8h à 12h 

In [236]:
print(temp_journee[8:13])

[25 22 33 44 38]


##### 5) les températures des 6 premières heures 

In [237]:
print(temp_journee[:6])

[22 39 36 30 30 41]


##### 6) les températures des heures paires

In [238]:
print(temp_journee[::2])

[22 36 30 22 25 33 38 37 32 40 32 24]
