### Partie 1 : Listes Python vs tableaux NumPy 

#### 1) Créer une liste Python stockant ces températures; 

In [11]:
import numpy as np
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8 ]
print (temperatures)

[24.5, 25.1, 26.3, 27.0, 25.8]


#### 2) Créer un tableau NumPy équivalent stockant ces températures ;

In [14]:
temperatures = np.array([24.5, 25.1, 26.3, 27.0, 25.8 ])
print(temperatures)

[24.5 25.1 26.3 27.  25.8]


#### 3) Effectuer une multiplication par 2 sur ces deux collections; 

---pour la liste---

In [12]:
mult_liste_temp = temperatures * 2
print(mult_liste_temp)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]


---pour le tableau---

In [15]:
mult_tableau_temp = temperatures * 2
print (mult_tableau_temp)

[49.  50.2 52.6 54.  51.6]


#### 4) Quelle différence observe-t-on ? 

Pour la liste : nous constatons qu'il y'a une duplication de la liste ,les valeurs sont repetes deux fois .
Et pour le tableau : nous constatons un nouveau tableau avec des valeurs multipliees chacune par 2.

### Partie 2 – Création des données 

#### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3) Créer un tableau de 10 valeurs initialisées à 25. 


In [18]:
np.full(10,25)

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

#### 4) Créer une matrice identité de taille 5 × 5. 

In [21]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])