### Partie 1 : Listes Python vs tableaux NumPy 

#### 1) Créer une liste Python stockant ces températures; 

In [4]:
import numpy as np
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8 ]
print (temperatures)

[24.5, 25.1, 26.3, 27.0, 25.8]


#### 2) Créer un tableau NumPy équivalent stockant ces températures ;

In [5]:
temperatures = np.array([24.5, 25.1, 26.3, 27.0, 25.8 ])
print(temperatures)

[24.5 25.1 26.3 27.  25.8]


#### 3) Effectuer une multiplication par 2 sur ces deux collections; 

---pour la liste---

In [7]:
mult_liste_temp = temperatures * 2
print(mult_liste_temp)

[49.  50.2 52.6 54.  51.6]


---pour le tableau---

In [8]:
mult_tableau_temp = temperatures * 2
print (mult_tableau_temp)

[49.  50.2 52.6 54.  51.6]


#### 4) Quelle différence observe-t-on ? 

Pour la liste : nous constatons qu'il y'a une duplication de la liste ,les valeurs sont repetes deux fois .
Et pour le tableau : nous constatons un nouveau tableau avec des valeurs multipliees chacune par 2.

### Partie 2 – Création des données 

#### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [9]:
tableau_zero = np.zeros(10)
print(tableau_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [10]:
tableau_un = np.ones(10)
print(tableau_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 3) Créer un tableau de 10 valeurs initialisées à 25. 


In [11]:
val = np.full(10,25)
print(val)

[25 25 25 25 25 25 25 25 25 25]


#### 4) Créer une matrice identité de taille 5 × 5. 

In [12]:
identite = np.eye(5,5)
print(identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [13]:
heures = np.arange(0,24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [14]:
tableau_repartie = np.linspace(20,30,10 , dtype=int)
print(tableau_repartie)

[20 21 22 23 24 25 26 27 28 30]


#### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [15]:
rng = np.random.default_rng(seed=42)
temperature = rng.random(100)
print(temperature)


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
 0.7611397  0.78606431 0.12811363 0.45038594 0.37079802 0.92676499
 0.64386512 0.82276161 0.4434142  0.22723872 0.55458479 0.06381726
 0.82763117 0.6316644  0.75808774 0.35452597 0.97069802 0.89312112
 0.7783835  0.19463871 0.466721   0.04380377 0.15428949 0.68304895
 0.74476216 0.96750973 0.32582536 0.37045971 0.46955581 0.18947136
 0.12992151 0.47570493 0.22690935 0.66981399 0.43715192 0.8326782
 0.7002651  0.31236664 0.8322598  0.80476436 0.38747838 0.2883281
 0.6824955  0.13975248 0.1999082  0.00736227 0.78692438 0.66485086
 0.70516538 0.78072903 0.45891578 0.5687412  0.139797   0.11453007
 0.66840296 0.47109621 0.56523611 0.76499886 0.63471832 0.5535794
 0.55920716 0.3039501  0.03081783 0.43671739 0.21458467 0.40852864
 0.85340307 0.23393949 0.05830274 0.28138389 0.29359376 0.66191651
 0.55703215 0.78389821 0.66431354 0.40638686 0.81402038 0.16697292
 0.02271207 0.09004786 0.72235935 0.46187723 0.16127178 0.5010447

**Explication**: ici pour generer aleatoirement les temperatures de 100 mesures en rendant les resultat reproductibles , on initialise une graine "seed" qu'on choisi de fixer ici 42. cette initialisation permet de fixer un point de depart pour que la machine puisse toujours generer les memes 100 temperatures dans le meme ordre sur n'importe quel machine. 

### Partie 3 – Exploration des tableaux 

#### 1) Créer aléatoirement un tableau représentant les 24 températures d'une journée : 

In [16]:
rng = np.random.default_rng(seed=42)
temp_journee = rng.integers(20,45,24)
print(temp_journee)

[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]


#### 2) Déterminer les propriétés suivantes du tableau 
##### a) nombre de dimensions 

In [17]:
nb_dimensions = temp_journee.ndim
print(nb_dimensions)

1


***explication*** : le resultat indique qu'il y'a une seule dimension c'est a dire une simple liste

##### b) nombre de valeurs ; 

In [18]:
nb_val = temp_journee.size
print(nb_val)

24


***explication*** : ce resultat indique que cette liste contient 24 valeurs

##### c) type des données 

In [19]:
type_donnee = temp_journee.dtype
print(type_donnee)

int64


***explication*** : ce resultat indique le type des donnees et nous pouvons constater que les donnees sont de type int.

##### d) forme du tableau

In [20]:
forme_tab = temp_journee.shape
print(forme_tab)

(24,)


***explication*** : ce resultat nous indique qu'il y'a un seule axe contenant 24 elements

### Partie 4 – Indexation et slicing 

##### 1) la première mesure 

In [21]:
print(temp_journee[0])

22


***explication*** : le resultat 22 represente la premiere temperature a l'indice 0

##### 2) la dernière mesure 

In [22]:
print(temp_journee[-1])

43


***explication*** : le resultat 43 represente la derniere temperature a l'indice -1

##### 3) la température de 8h 

In [23]:
print(temp_journee[8])

25


***explication*** : le resultat 25 represente la temperature de 8h a l'indice 8. 

##### 4) les températures de 8h à 12h 

In [24]:
print(temp_journee[8:13])

[25 22 33 44 38]


***explication*** : ce resultat represente les temperatures de 8h a 12h .temp_journee[8:13] permet d'extraire les temperatures de 8h à 12h incluses. On s'arrête à l'indice 13 car la borne de fin est toujours exclue en Python .

##### 5) les températures des 6 premières heures 

In [25]:
print(temp_journee[:6])

[22 39 36 30 30 41]


***explication***: temp_journee[:6] permet d'extraire les 6 premières températures des 6 premieres heures .Omettre le chiffre avant les deux-points signifie qu'on démarre tout au debut a l'indice 0.

##### 6) les températures des heures paires

In [26]:
print(temp_journee[::2])

[22 36 30 22 25 33 38 37 32 40 32 24]


***explication*** : temp_journee[::2] permet d'extraire les températures des heures paires. Le chiffre 2 à la fin indique le pas c'est a dire qu'on parcourt tout le tableau en avançant par pas de 2.

### Partie 5 – Filtrage booléen 

##### 1) Afficher les températures supérieures à 30 °C 

In [27]:
temp_sup_30 = temp_journee[temp_journee > 30]
print(temp_sup_30)

[39 36 41 37 33 44 38 39 37 39 32 40 31 32 43]


##### 2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C 

In [28]:
temp_normale = temp_journee[(temp_journee>20) & (temp_journee<30)]
print(temp_normale)

[22 22 25 22 23 29 24]


##### 3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 

In [29]:
anomalies = temp_journee > 35
print (anomalies)

[False  True  True False False  True False  True False False False  True
  True  True  True  True False False  True False False False False  True]


***explication***: on a un resultat d'un tableau booleen dont les "True" representent les anomalies c'est a dire les temperatures superieures a 35 et les "False" representent les temperatures normales c'est a dire les temperatures inferieures ou egales a 35.

##### 4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies 

In [30]:
nb_anormales = np.sum(anomalies)
print(nb_anormales)

11


***explication*** : En Python et NumPy, les valeurs booléennes sont traitées numériquement : ce qui fait que True vaut 1 et False vaut 0.
Ainsi, la fonction sum(anomalies) additionne tous les 1 (les True), ce qui donne exactement le nombre total de températures supérieures à 35 °C.

### Partie 6 – Manipulation des dimensions 

##### 1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée 

In [63]:
rng = np.random.default_rng(seed=42)
matrice_temp = rng.integers(20,45,size=(5,24))
print(matrice_temp)

[[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]
 [39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42]
 [36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24]
 [31 23 37 31 28 25 34 36 43 30 24 40 35 37 22 27 39 40 30 40 41 29 42 27]
 [25 37 35 23 40 24 40 20 39 39 39 36 31 37 26 39 33 31 32 34 20 23 26 22]]


##### 2) Transformer la matrice en un tableau unidimensionnel

In [64]:
matrice_unidim = matrice_temp.flatten()
print(matrice_unidim)

[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43
 39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42
 36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24
 31 23 37 31 28 25 34 36 43 30 24 40 35 37 22 27 39 40 30 40 41 29 42 27
 25 37 35 23 40 24 40 20 39 39 39 36 31 37 26 39 33 31 32 34 20 23 26 22]


##### 3) Déterminer la transposée de la matrice 

In [66]:
matrice_transposee = np.transpose(matrice_temp)
print(matrice_transposee)

[[22 39 36 31 25]
 [39 36 39 23 37]
 [36 30 38 37 35]
 [30 40 24 31 23]
 [30 33 29 28 40]
 [41 31 31 25 24]
 [22 31 32 34 40]
 [37 25 21 36 20]
 [25 22 33 43 39]
 [22 33 23 30 39]
 [33 42 38 24 39]
 [44 21 37 40 36]
 [38 41 43 35 31]
 [39 40 38 37 37]
 [37 26 29 22 26]
 [39 35 44 27 39]
 [32 24 30 39 33]
 [23 38 28 40 31]
 [40 37 42 30 32]
 [31 28 29 40 34]
 [32 21 21 41 20]
 [29 44 31 29 23]
 [24 31 39 42 26]
 [43 42 24 27 22]]


***explication*** : Dans la matrice initiale matrice_temp, la ligne i contenait les 24 températures relevées par le capteur i.
Dans la matrice transposée matrice_transposee, la ligne j contient maintenant les températures relevées par les 5 capteurs à l'heure j.

##### 4) Extraire toutes les mesures du capteur 1 

In [67]:
mesures_capteur_1 = matrice_temp[0, :]
print(mesures_capteur_1)

[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]


***explication***: matrice_temp[0, :]
0 (avant la virgule) : permet de sélectionner uniquement la première ligne (le capteur 1) a l'indice 0.
: (après la virgule) : permet de sélectionner l'intégralité des colonnes c'est a dire pour toute les colonnes (les 24 heures de la journée).

##### 5) Extraire toutes les mesures du capteur 5 

In [68]:
mesures_capteur_5 = matrice_temp[4, :]
print(mesures_capteur_5)

[25 37 35 23 40 24 40 20 39 39 39 36 31 37 26 39 33 31 32 34 20 23 26 22]


***explication***: matrice_temp[4, :]
4 (avant la virgule) : permet de sélectionner uniquement la première ligne (le capteur 5) a l'indice 4.
: (après la virgule) : permet de sélectionner l'intégralité des colonnes c'est a dire pour toute les colonnes (les 24 heures de la journée).

##### 6) Extraire les mesures de tous les capteurs à 10h 

In [69]:
mesures_cap = matrice_temp[: ,10]
print(mesures_cap)

[33 42 38 24 39]


***explication*** : 
: (avant la virgule) signifie qu'on conserve toutes les lignes (c'est-à-dire l'ensemble des 5 capteurs).
10 (après la virgule) cible uniquement la 11ᵉ colonne (l'index 10 correspondant à la mesure effectuée à 10h).

##### 7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h

In [72]:
mesures_caps = matrice_temp[1:4, 8:13]
print(mesures_caps)

[[22 33 42 21 41]
 [33 23 38 37 43]
 [43 30 24 40 35]]


### Partie 7 – Concaténation 

##### 1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée 

In [74]:
rng=np.random.default_rng(seed=42)
matrice_snd_batiment = rng.integers(20,45,size=(3,24))
print(matrice_snd_batiment)

[[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]
 [39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42]
 [36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24]]


##### 2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée 

##### Premiere methode :

In [75]:
matrice_fusion_1 = np.vstack((matrice_temp, matrice_snd_batiment))
print(matrice_fusion_1)

[[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]
 [39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42]
 [36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24]
 [31 23 37 31 28 25 34 36 43 30 24 40 35 37 22 27 39 40 30 40 41 29 42 27]
 [25 37 35 23 40 24 40 20 39 39 39 36 31 37 26 39 33 31 32 34 20 23 26 22]
 [22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]
 [39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42]
 [36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24]]


##### Deuxieme methode :

In [81]:
matrice_fusion_2 = np.concatenate((matrice_temp, matrice_snd_batiment), axis=0)
print(matrice_fusion_2)

[[22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]
 [39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42]
 [36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24]
 [31 23 37 31 28 25 34 36 43 30 24 40 35 37 22 27 39 40 30 40 41 29 42 27]
 [25 37 35 23 40 24 40 20 39 39 39 36 31 37 26 39 33 31 32 34 20 23 26 22]
 [22 39 36 30 30 41 22 37 25 22 33 44 38 39 37 39 32 23 40 31 32 29 24 43]
 [39 36 30 40 33 31 31 25 22 33 42 21 41 40 26 35 24 38 37 28 21 44 31 42]
 [36 39 38 24 29 31 32 21 33 23 38 37 43 38 29 44 30 28 42 29 21 31 39 24]]


### Partie 8 : Calcul scientifique 

##### 1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l’écart-type 

#####  calcule du minimum

In [86]:
mesure_min = np.min(matrice_temp)
print(mesure_min)

20


***explication*** : cette valeur represente la valeur la plus petite de la matrice matrice_temp

##### calcule du maximum

In [88]:
mesure_max = np.max(matrice_temp)
print(mesure_max)

44


***explication*** : cette valeur represente la valeur la plus grande de la matrice matrice_temp